### ISSUE TITLE
Lookup by vendor name

### ISSUE THREAD

**Issue by dansou901** [JDSlimz/pcilookup#1]
Hi,
on pcidatabase.com, I could actually browse through the database. Is that also planned for pcilookup? Or will this be only for simple lookup?
Regards,
dansou901

**Comment by JDSlimz** [comment]
This is now in the works and should be live within a few days! Thanks!

**Comment by JDSlimz** [comment]
Apologies for the delay, we are working on the front-end now. Lots of personal and work life inhibiting coding time.

**Comment by JDSlimz** [comment]
This has been completed!
